#!/bin/sh

# Check possible problems in the MPFR source.

grep '^# *include *<math\.h>' *.c

grep -E 'mpfr_(underflow|overflow|nanflag|inexflag|erangeflag)_p' *.{c,h} | \
  grep -v '^exceptions.c:' | grep -v '^mpfr-impl.h:#define mpfr_.*_p()' | \
  grep -v '^mpfr.h:__MPFR_DECLSPEC '

grep -E 'if +(test|\[).* == ' acinclude.m4 configure.in
grep -E '="`' acinclude.m4 configure.in

grep GMP_RND {,tests/}*.{c,h} | grep -v '#define GMP_RND'

grep mp_rnd_t {,tests/}*.{c,h} | grep -v '# *\(define\|ifndef\) *mp_rnd_t'

fdlv1="`sed -n '/Version / {s/.*Version //; s/,.*//; p; q}' fdl.texi`"
fdlv2="`sed -n '/GNU Free Documentation License/ \
  {s/.*Version //; s/ or.*//; p; q}' mpfr.texi`"
[ "x$fdlv1" = "x$fdlv2" ] || cat <<EOF
GFDL versions differ:
   fdl.texi: $fdlv1
  mpfr.texi: $fdlv2
EOF

# Note: if paragraphs are reformatted, this may need to be updated.
lgpl="`sed -n '/version [0-9.]\+ or any later version/ \
  {s/.*version //; s/ or.*//; p; q}' mpfr.texi`"
for file in {,tests/}*.{c,h}
do
  [ "$file" = "get_patches.c" ] && file="get_patches.sh"
  if grep -q "GNU MPFR Library" "$file"; then
    grep -q "either version $lgpl of the License" "$file" || \
      echo "Possibly missing or incorrect copyright notice in $file"
  fi
done

texisvnd=`TZ=UTC svn info mpfr.texi 2> /dev/null | sed -n 's/Last Changed Date:.*, [0-9]* \([A-Z][a-z][a-z] [0-9][0-9][0-9][0-9]\)).*/\1/p'`
if [ $? -eq 0 ] && [ -n "$texisvnd" ]; then
  texidate=`sed -n 's/@set UPDATED-MONTH \([A-Z][a-z][a-z]\).*\( [0-9][0-9][0-9][0-9]\)/\1\2/p' mpfr.texi`
  cat <<EOF
mpfr.texi's UPDATED-MONTH seems to be incorrect:
  mpfr.texi's UPDATED-MONTH: $texidate
  Last Changed Date in WC:   $texisvnd
EOF
fi

true
