#!/bin/csh
# Usage: nightly-test <GMPDIR>
set GMP=$1
set DIR=mpfr-nightly
cd /tmp
/bin/rm -fr $DIR
mkdir $DIR
cd $DIR
svn checkout svn://scm.gforge.inria.fr/svn/mpfr/trunk mpfr
cd mpfr
autoreconf -i
./configure --disable-alloca --enable-assert --with-gmp=$GMP --disable-shared --enable-thread-safe
make
make check
cd /tmp
/bin/rm -fr $DIR

