#!/bin/sh --

if test x"$1" = x"-dev" ; then
  include_deps=
  shift
else
  include_deps="-i"
fi

if aclocal \
  && automake --gnu Makefile $include_deps \
  && automake --gnu tests/Makefile $include_deps \
  && autoconf && ./configure $@
then
  echo
  echo "The MPFR source code was successfully prepared."
  echo "Type make to build MPFR."
  echo
else
  echo
  echo "Some part of the preparation process failed."
  echo
  exit 1
fi
