#!/bin/sh --

# This script is inspired by the prepare script distributed with Mutt.

if test x"$1" = x"-dev" ; then
  include_deps=
  shift
else
  include_deps="-i"
fi

if libtoolize --automake --copy && aclocal && automake $include_deps --copy --add-missing && autoconf && ./configure $@
then
  echo
  echo "The MPFR source code was successfully prepared."
  echo "Type 'make' to build MPFR."
  echo
  echo "Note: if you want to reconfigure MPFR, you can now use the 'configure'"
  echo "script directly; you do not need the 'prepare' script any longer."
  echo
else
  echo
  echo "Some part of the preparation process failed."
  echo
  exit 1
fi
