#!/bin/sh

set -e

if [ $# -ne 1 ]; then
  echo "Usage: $0 <patchnumber>"
  exit 1
fi

vers="`perl -pe 's/^(\d+\.\d+\.\d+).*/\1/' VERSION`"
full="${vers}-p$1"
echo $full > VERSION
perl -pi -e "s/(?<=#define MPFR_VERSION_STRING ).*/\"$full\"/" mpfr.h
perl -pi -e "s/(?<=return \").*\"/$full\"/" version.c
perl -pi -e "s/(?<=#if ).*/0/" tests/tversion.c

echo "MPFR version successfully updated."
