#!/bin/sh

# ck-copyright-notice can be run from the tools directory
dir=`pwd`
[ -d src ] || [ "`basename "$dir"`" != tools ] || cd ..

# Note: if paragraphs are reformatted, this may need to be updated.

lgpl="`sed -n '/version [0-9.]* or any later version/ {
  s/.*version //
  s/ or.*//
  p
  q
  }' doc/mpfr.texi`"

# Do not use "find ... | while read file do ... done" because the "do"
# part needs to be run in the current shell, and some shells behave in
# a different way.
srctests=`find src tests -name '*.[ch]'`

err=0
for file in $srctests
do
  y=""
  case $file in
    tests/RRTest.c)
      continue ;;
    src/get_patches.c)
      file="tools/get_patches.sh" ;;
    */mparam.h)
      y="2005," ;;
  esac
  grep -q "Copyright $y.* Free Software Foundation" "$file" && \
  grep -q "GNU MPFR Library" "$file" && \
  grep -q "either version $lgpl of the License" "$file" && continue
  echo "Possibly missing or incorrect copyright notice in $file"
  err=1
done

exit $err
