#!/bin/sh

# For gitlog-to-changelog, use the '%B%n' format string rather than the
# default '%s%n%b%n' because Git's commit message convention is not always
# followed (in particular before the conversion of the repository to Git).
# When it isn't, this makes the text much more readable for the concerned
# commits. The only minor drawback is that this makes the ChangeLog file
# about 1% larger.

# This script can be run from the tools directory.
[ -d tools ] || [ "$(basename "$(pwd)")" != tools ] || cd ..

TZ=UTC0
export TZ

tools/gitlog-to-changelog --ignore-line='\[From SVN r.*\]' \
                          --strip-cherry-pick --format='%B%n' > ChangeLog
